ALTER SESSION SET CURRENT_SCHEMA = SYSDBA;
	SET SQLBLANKLINES ON
	SET SQLTERMINATOR ';'
CREATE TABLE SYSDBA.FURER
	(
	FURERID  CHAR(12 BYTE) NOT NULL
	);
	exec SYSDBA.FB_INSERT_INTO_SECTABLES ('FURER','FURERID','WHERE THE COMMENT?');COMMIT;
