ALTER SESSION SET CURRENT_SCHEMA = SYSDBA;
	SET SQLBLANKLINES ON
	SET SQLTERMINATOR ';'
CREATE TABLE SYSDBA.KPSS
	(
	KPSSID  CHAR(12 BYTE) NOT NULL
	);
	exec SYSDBA.FB_INSERT_INTO_SECTABLES ('KPSS','KPSSID','WHERE THE COMMENT?');COMMIT;
