ALTER SESSION SET CURRENT_SCHEMA = SYSDBA;
	SET SQLBLANKLINES ON
	SET SQLTERMINATOR ';'
exec SYSDBA.FB_DROP_FIELD_FROM_SECTABLES ('KPSS', 'STATUS');
 ALTER TABLE SYSDBA.KPSS DROP COLUMN STATUS;
exec SYSDBA.FB_DROP_FIELD_FROM_SECTABLES ('KPSS', 'WHERE');
 ALTER TABLE SYSDBA.KPSS DROP COLUMN WHERE;
COMMIT;
