ALTER SESSION SET CURRENT_SCHEMA = SYSDBA;
	SET SQLBLANKLINES ON
	SET SQLTERMINATOR ';'
exec SYSDBA.FB_DROP_FIELD_FROM_SECTABLES ('GORODOK', 'MODIFYDATE');
 ALTER TABLE SYSDBA.GORODOK DROP COLUMN MODIFYDATE;
exec SYSDBA.FB_DROP_FIELD_FROM_SECTABLES ('GORODOK', 'GDE');
 ALTER TABLE SYSDBA.GORODOK DROP COLUMN GDE;
COMMIT;
